---
title: "PLACES Exploration"
author: "Toyin Ola"
date: "`r format(Sys.time(), ' %B %d, %Y')`"
output: 
  html_document:
    css: style.css
    theme: cerulean
    toc: true
    toc_float: 
      collapsed: false
editor_options: 
  
  chunk_output_type: console
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, comment = NA, include = FALSE, cache = FALSE)

```

# Overview

The [Population Level Analysis and Community Estimates (PLACES) data set](https://www.cdc.gov/places/index.html) is the result of multi-level regression modelling on Behavioral Risk Factor Surveillance Survey (BRFSS) and American Community Survey (ACS) data. Thanks to this modelling, population-health estimates are available for small geographic areas like counties, Census tracts, zip code tabulation areas, etc. See more information about the modelling process in the [methodology](https://www.cdc.gov/places/methodology/index.html). 

The PLACES data set has incredibly robust documentation. Crude and age-adjusted prevalence rates are included for each of the 29 measures in the data set. Measures are grouped into four categories: health outcomes, prevention, health risk behaviors, and health status. The [measure definitions](https://www.cdc.gov/places/measure-definitions/index.html) page include detailed explanations for each measure, including numerator, denominator, case period time definition, data source(s), data limitations, additional resources, etc.

The [latest PLACES data set](https://chronicdata.cdc.gov/500-Cities-Places/PLACES-Local-Data-for-Better-Health-County-Data-20/swc5-untb) is the 2022 release. There are multiple years in the CDC PLACES data set. It is important to use the latest release as errors are sometimes corrected; see [changelog](https://www.cdc.gov/places/help/data-notes/index.html). There is an [API](https://chronicdata.cdc.gov/resource/swc5-untb.json) that can be used to obtain the data. See the [API documentation](https://dev.socrata.com/foundry/chronicdata.cdc.gov/swc5-untb) for filtering options.

It is important to note that PLACES is an extension of the [500 Cities Project](https://www.cdc.gov/places/about/500-cities-2016-2019/index.html), which was operational form 2016-2019. PLACES replaced the 500 Cities Project in December 2020.

# Measures

[Health Outcomes Measures](https://www.cdc.gov/places/measure-definitions/health-outcomes/index.html)
Arthritis among adults aged ≥18 years
Current asthma prevalence among adults aged ≥18 years
High blood pressure among adults aged ≥18 years
Cancer among adults aged ≥18 years
High cholesterol among adults aged ≥18 years who have been screened in the past 5 years
Chronic kidney disease among adults aged ≥18 years
Chronic obstructive pulmonary disease among adults aged ≥18 years
Coronary heart disease among adults aged ≥18 years
Depression among adults aged ≥18 years
Diagnosed diabetes among adults aged ≥18 years
Obesity among adults aged ≥18 years
All teeth lost among adults aged ≥65 years
Stroke among adults aged ≥18 years

[Prevention Measures](https://www.cdc.gov/places/measure-definitions/prevention/index.html)
Current lack of health insurance among adults aged 18–64 years
Visits to doctor for routine checkup within the past year among adults aged ≥18 years
Visits to dentist or dental clinic among adults aged ≥18 years
Taking medicine for high blood pressure control among adults aged ≥18 years with high blood pressure
Cholesterol screening among adults aged ≥18 years
Mammography use among women aged 50-74 years
Cervical cancer screening among adult women aged 21–65 years
Fecal occult blood test, sigmoidoscopy, or colonoscopy among adults aged 50–75 years
Older adults aged ≥65 years who are up to date on a core set of clinical preventive services by age and sex

[Health Risk Behaviors Measures](https://www.cdc.gov/places/measure-definitions/unhealthy-behaviors/index.html)
Binge drinking among adults aged ≥18 years
Current smoking among adults aged ≥18 years
No leisure-time physical activity among adults aged ≥18 years
Sleeping less than 7 hours among adults aged ≥18 years

[Health Status Measures](https://www.cdc.gov/places/measure-definitions/health-status/index.html)
Mental health not good for ≥14 days among adults aged ≥18 years
Physical health not good for ≥14 days among adults aged ≥18 years
Fair or poor self-rated health status among adults aged ≥18 years
